# Generated by Django 5.2.4 on 2025-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
